const configObj = {
    tomcatObj: {
        7: {
            wasHome: "D:/NANUM/WAS/apache-tomcat-7.0.91",
            lib: [
                "lib/annotations-api.jar",
                "lib/catalina-ant.jar",
                "lib/catalina-ha.jar",
                "lib/catalina-tribes.jar",
                "lib/catalina.jar",
                "lib/ecj-4.4.2.jar",
                "lib/el-api.jar",
                "lib/jasper-el.jar",
                "lib/jasper.jar",
                "lib/jsp-api.jar",
                "lib/servlet-api.jar",
                "lib/tomcat-api.jar",
                "lib/tomcat-coyote.jar",
                "lib/tomcat-dbcp.jar",
                "lib/tomcat-i18n-es.jar",
                "lib/tomcat-i18n-fr.jar",
                "lib/tomcat-i18n-ja.jar",
                "lib/tomcat-i18n-ru.jar",
                "lib/tomcat-jdbc.jar",
                "lib/tomcat-util.jar",
                "lib/tomcat7-websocket.jar",
                "lib/websocket-api.jar",
            ],
        },
        8: {
            wasHome: "D:/NANUM/WAS/apache-tomcat-8.0.53",
            lib: [
                "lib/annotations-api.jar",
                "lib/catalina-ant.jar",
                "lib/catalina-ha.jar",
                "lib/catalina-storeconfig.jar",
                "lib/catalina-tribes.jar",
                "lib/catalina.jar",
                "lib/ecj-4.6.3.jar",
                "lib/el-api.jar",
                "lib/jasper-el.jar",
                "lib/jasper.jar",
                "lib/jsp-api.jar",
                "lib/servlet-api.jar",
                "lib/tomcat-api.jar",
                "lib/tomcat-coyote.jar",
                "lib/tomcat-dbcp.jar",
                "lib/tomcat-i18n-es.jar",
                "lib/tomcat-i18n-fr.jar",
                "lib/tomcat-i18n-ja.jar",
                "lib/tomcat-jdbc.jar",
                "lib/tomcat-jni.jar",
                "lib/tomcat-util-scan.jar",
                "lib/tomcat-util.jar",
                "lib/tomcat-websocket.jar",
                "lib/websocket-api.jar",
            ],
        },
        9: {
            wasHome: "D:/NANUM/WAS/apache-tomcat-9.0.63",
            lib: [
                "lib/annotations-api.jar",
                "lib/catalina-ant.jar",
                "lib/catalina-ha.jar",
                "lib/catalina-ssi.jar",
                "lib/catalina-storeconfig.jar",
                "lib/catalina-tribes.jar",
                "lib/catalina.jar",
                "lib/ecj-4.20.jar",
                "lib/el-api.jar",
                "lib/jasper-el.jar",
                "lib/jasper.jar",
                "lib/jaspic-api.jar",
                "lib/jsp-api.jar",
                "lib/jstl-1.2.jar",
                "lib/servlet-api.jar",
                "lib/tomcat-api.jar",
                "lib/tomcat-coyote.jar",
                "lib/tomcat-dbcp.jar",
                "lib/tomcat-i18n-cs.jar",
                "lib/tomcat-i18n-de.jar",
                "lib/tomcat-i18n-es.jar",
                "lib/tomcat-i18n-fr.jar",
                "lib/tomcat-i18n-ja.jar",
                "lib/tomcat-i18n-ko.jar",
                "lib/tomcat-i18n-pt-BR.jar",
                "lib/tomcat-i18n-ru.jar",
                "lib/tomcat-i18n-zh-CN.jar",
                "lib/tomcat-jdbc.jar",
                "lib/tomcat-jni.jar",
                "lib/tomcat-util-scan.jar",
                "lib/tomcat-util.jar",
                "lib/tomcat-websocket.jar",
                "lib/websocket-api.jar",
            ],
        },
    },
    workAndProjectName: "DTRO\\SmartFlowOSE3.5",
    workSpaces: "D:\\NANUM\\workspaces",
    vmConfig: [
        "com.caucho.server.resin.Resin",
        '-conf "!\\#\\resin.conf" ',
        "",
        "-Djava.util.logging.manager=com.caucho.log.LogManagerImpl",
        "-Djavax.management.builder.initial=com.caucho.jmx.MBeanServerBuilderImpl",
        '-Dresin.home="D:\\NANUM\\WAS\\resin-3.0.23"',
        "",
        "-DXF_HOME=!\\#",
        "-DNANUM_HOME=!\\#",
        "-DNBRM_HOME=!\\#",
    ],
};
